import Head from "next/head";
import Image from "next/image";

import IntroductionBanner from "@/pages/introduction-banner.jsx";
import EducationSection from "@/pages/education-section.jsx";
import TechSection from "@/pages//tech-section";
import ProjectSection from "@/pages/project-section.jsx";
import ContactSection from "./contact-section";

import styles from "@/styles/Home.module.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<IntroductionBanner id="home" />
<EducationSection id="degrees" />
<TechSection id="tech" />
<ProjectSection id="projects" />
<ContactSection id="contact" />


    </>
  );
}
